### ISSUE TITLE
Broken Docker image

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/documentation#12]
You can't build the Docker image anymore. See below.

```
$ docker build -t docs .
[+] Building 5.6s (8/8) FINISHED                                                                                                        
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 183B                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 2B                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:2.7                                                                      1.6s
 => [internal] load build context                                                                                                  0.3s
 => => transferring context: 28.97MB                                                                                               0.3s
 => CACHED [1/4] FROM docker.io/library/python:2.7@sha256:cfa62318c459b1fde9e0841c619906d15ada5910d625176e24bf692cf8a2601d         0.0s
 => [2/4] COPY . /OC.DOCS/                                                                                                         0.1s
 => [3/4] WORKDIR /OC.DOCS/                                                                                                        0.0s
 => ERROR [4/4] RUN pip install mkdocs                                                                                             3.5s
------                                                                                                                                  
 > [4/4] RUN pip install mkdocs:                                                                                                        
#4 0.348 DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                                                  
#4 0.471 Collecting mkdocs                                                                                                              
#4 0.538   Downloading mkdocs-1.0.4-py2.py3-none-any.whl (1.2 MB)
#4 0.685 Collecting Markdown>=2.3.1
#4 0.701   Downloading Markdown-3.1.1-py2.py3-none-any.whl (87 kB)
#4 0.740 Collecting livereload>=2.5.1
#4 0.756   Downloading livereload-2.6.3-py2.py3-none-any.whl (24 kB)
#4 0.854 Collecting tornado>=5.0
#4 0.871   Downloading tornado-5.1.1.tar.gz (516 kB)
#4 1.069 Collecting Jinja2>=2.7.1
#4 1.086   Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
#4 1.135 Collecting click>=3.3
#4 1.151   Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
#4 1.256 Collecting PyYAML>=3.10
#4 1.271   Downloading PyYAML-5.4.1.tar.gz (175 kB)
#4 1.354   Installing build dependencies: started
#4 3.322   Installing build dependencies: finished with status 'done'
#4 3.323   Getting requirements to build wheel: started
#4 3.436   Getting requirements to build wheel: finished with status 'error'
#4 3.436   ERROR: Command errored out with exit status 1:
#4 3.436    command: /usr/local/bin/python /usr/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsxRoru
#4 3.436        cwd: /tmp/pip-install-8KG2zm/PyYAML
#4 3.436   Complete output (46 lines):
#4 3.436   running egg_info
#4 3.436   creating lib/PyYAML.egg-info
#4 3.436   writing lib/PyYAML.egg-info/PKG-INFO
#4 3.436   writing top-level names to lib/PyYAML.egg-info/top_level.txt
#4 3.436   writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
#4 3.436   writing manifest file 'lib/PyYAML.egg-info/SOURCES.txt'
#4 3.436   Traceback (most recent call last):
#4 3.436     File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
#4 3.436       main()
#4 3.436     File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
#4 3.436       json_out['return_val'] = hook(**hook_input['kwargs'])
#4 3.436     File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
#4 3.436       return hook(config_settings)
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
#4 3.436       return self._get_build_requires(config_settings, requirements=['wheel'])
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
#4 3.436       self.run_setup()
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
#4 3.436       exec(compile(code, __file__, 'exec'), locals())
#4 3.436     File "setup.py", line 295, in <module>
#4 3.436       python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
#4 3.436       return distutils.core.setup(**attrs)
#4 3.436     File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
#4 3.436       dist.run_commands()
#4 3.436     File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
#4 3.436       self.run_command(cmd)
#4 3.436     File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
#4 3.436       cmd_obj.run()
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
#4 3.436       self.find_sources()
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
#4 3.436       mm.run()
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
#4 3.436       self.add_defaults()
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
#4 3.436       sdist.add_defaults(self)
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
#4 3.436       self._add_defaults_ext()
#4 3.436     File "/tmp/pip-build-env-QUfB9q/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 120, in _add_defaults_ext
#4 3.436       self.filelist.extend(build_ext.get_source_files())
#4 3.436     File "setup.py", line 201, in get_source_files
#4 3.436       self.cython_sources(ext.sources, ext)
#4 3.436     File "/usr/local/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
#4 3.436       raise AttributeError, attr
#4 3.436   AttributeError: cython_sources
#4 3.436   ----------------------------------------
#4 3.465 ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsxRoru Check the logs for full command output.
#4 3.474 WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
#4 3.474 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
process "/bin/sh -c pip install mkdocs" did not complete successfully: exit code: 1
```

**Comment by c0c0n3** [comment]
The problem is that we have no explicit `pip` and `mkdocs` versions in the Docker file. Rather than fixing this, migrate to Nix, which is a much better tech, it actually ensures build reproducibility and also gives you reproducible, isolated, *local* build envs w/o the annoyance of having to run Docker containers.
